// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using DependencyInjectionSimple.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DependencyInjectionConsoleApplication.Data.Configurations
{
    public partial class CustomersConfiguration : IEntityTypeConfiguration<Customers>
    {
        public void Configure(EntityTypeBuilder<Customers> entity)
        {
            entity.Property(e => e.FirstName).IsRequired();

            entity.Property(e => e.LastName).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customers> entity);
    }
}
