// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using DependencyInjectionConsoleApplication.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DependencyInjectionConsoleApplication.Data.Configurations
{
    public partial class ProductsConfiguration : IEntityTypeConfiguration<Products>
    {
        public void Configure(EntityTypeBuilder<Products> entity)
        {
            entity.Property(e => e.Name).IsRequired();

            entity.Property(e => e.Price).HasColumnType("decimal(6, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Products> entity);
    }
}
